FROM ubuntu:22.04

RUN mkdir -p /app/data
WORKDIR /app

ADD requirements-torch.txt .

RUN apt-get update && apt-get install -qqy --no-install-recommends \
        python3 \
        python3-pip \
        python3-dev \
        python3-venv \
        && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv venv

RUN . venv/bin/activate && pip install -r requirements-torch.txt --no-cache-dir && deactivate