ARG TORCH_IMAGE=stablecog/sc-torch:latest
FROM $TORCH_IMAGE

RUN mkdir -p /app/data
WORKDIR /app

ADD requirements.txt .

RUN apt-get update && apt-get install -qqy --no-install-recommends \
        ca-certificates \
        wget \
        curl \
        git \
        ffmpeg \
        libgl1-mesa-glx \
        libglib2.0-0 \
        && rm -rf /var/lib/apt/lists/*

RUN . venv/bin/activate && pip install -r requirements.txt --no-cache-dir && deactivate