name: Deploy to Kubernetes
description: Deploy to Kubernetes
inputs:
  image:
    description: Image to deploy
    required: true
  kube_config:
    description: base64 encoded kube config
    required: true
runs:
  using: composite
  steps:
    - uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.5.4"

    - name: Set image
      working-directory: ./k8s
      shell: bash
      run: |
        kustomize edit set image replaceme=${{ inputs.image }}
        kustomize edit set replicas sc-worker=4
        kustomize build . > ci-deployment.yaml

    - name: Deploy image to k8s cluster
      uses: bbedward/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ inputs.kube_config }}
      with:
        args: apply -f ./k8s/ci-deployment.yaml
    
    - name: Wait for deployment to be ready
      uses: bbedward/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ inputs.kube_config }}
      with:
        args: rollout status deployment/sc-worker -n sc-worker

    - name: Scale down replicas
      working-directory: ./k8s
      shell: bash
      run: |
        kustomize edit set replicas sc-worker=2
        kustomize build . > ci-deployment.yaml

    - name: Redeploy with lower replica count
      uses: bbedward/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ inputs.kube_config }}
      with:
        args: apply -f ./k8s/ci-deployment.yaml