import os

WORKER_VERSION = "v2.01"
SHOULD_LOAD_KANDINSKY_2_1 = os.environ.get("LOAD_KANDINSKY_2_1", "1")
SHOULD_LOAD_KANDINSKY_2_2 = os.environ.get("LOAD_KANDINSKY_2_2", "1")
SHOULD_LOAD_KANDINSKY_SAFETY_CHECKER = os.environ.get("LOAD_SAFETY_CHECKER", "0")
